// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace HoloViewer.macOS
{
	public partial class ApplicationSettingsViewController : NSViewController
	{
		public bool Result { get; set; } = false;

		[Export(nameof(ApplicationSettings))]
		public ApplicationSettings ApplicationSettings { get; set; } = new ApplicationSettings();

		public ApplicationSettingsViewController (IntPtr handle) : base (handle)
		{
		}

        partial void ClickedCaptureSavePathButton(NSButton sender)
        {
			var panel = new NSOpenPanel();

			panel.CanChooseDirectories = true;
			panel.CanChooseFiles = false;

			if (panel.RunModal() == 1)
			{
				ApplicationSettings.CaptureSavePath = panel.Urls[0].Path;
			}
        }

        partial void ClickedOKButton(NSButton sender)
        {
			Result = true;
			ApplicationSettings.StartupPageUrl = StartupPageUrlTextFiled.StringValue;
			ApplicationSettings.CaptureSavePath = CaptureSavePathTextField.StringValue;
			View.Window.Close();
        }

        partial void ClickedCloseButton(NSButton sender)
		{
			Result = false;
			View.Window.Close();
		}
	}
}
