# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  create:
    tags:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '7.0.401'

      - name: Build Application for Windows
        run: dotnet publish ./HoloViewer/HoloViewer.csproj -c Release -f net7.0-windows10.0.22621.0

      - name: Build UpdateChecker
        run: dotnet publish ./UpdateChecker/UpdateChecker.csproj -c Release -f net7.0

      - name: Copy UpdateChecker
        run: copy ./UpdateChecker/bin/Release/net7.0/win-x64/publish/UpdateChecker.exe ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish

      - name: Delete Directory
        run: |
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/af-ZA
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ar-SA
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/az-Latn-AZ
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/bg-BG
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/bs-Latn-BA
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ca-ES
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/cs-CZ
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/cy-GB
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/da-DK
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/de-DE
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/el-GR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/en-GB
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/en-us
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/es-ES
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/es-MX
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/et-EE
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/eu-ES
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/fa-IR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/fi-FI
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/fr-CA
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/fr-FR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/gl-ES
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/he-IL
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/hi-IN
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/hr-HR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/hu-HU
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/id-ID
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/is-IS
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/it-IT
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ka-GE
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/kk-KZ
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ko-KR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/lt-LT
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/lv-LV
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/Microsoft.UI.Xaml
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ms-MY
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/nb-NO
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/nl-NL
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/nn-NO
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/pl-PL
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/pt-BR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/pt-PT
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ro-RO
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/ru-RU
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sk-SK
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sl-SI
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sq-AL
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sr-Cyrl-RS
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sr-Latn-RS
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/sv-SE
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/th-TH
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/tr-TR
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/uk-UA
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/vi-VN
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/zh-CN
            rmdir /s /q ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/zh-TW

      - name: Delete PDB Files
        run: del ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/*.pdb

      - name: Copy License File
        run: copy LICENSE ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/LICENCE

      - name: Create Windows Archive
        run: powershell Compress-Archive -Path ./HoloViewer/bin/Release/net7.0-windows10.0.22621.0/win10-x64/publish/* -DestinationPath HoloViewer_Windows_x64.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./HoloViewer_Windows_x64.zip
          asset_name: HoloViewer_Windows_x64.zip
          asset_content_type: application/zip