# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  create:
    tags:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with: 
          dotnet-version: '3.1.403'

      - name: Build Application for Windows
        run: dotnet publish -c Release ./HoloViewer.Windows/HoloViewer.Windows.csproj -r win-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true

      - name: Create Windows Archive
        run: powershell Compress-Archive -Path HoloViewer.Windows\bin\Release\netcoreapp3.1\win-x64\publish\* -DestinationPath HoloViewer_Windows_x64.zip

      - name: Upload Windows Archive
        uses: actions/upload-artifact@v2
        with:
          name: Windows_x64
          path: HoloViewer_Windows_x64.zip  

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
